// backend/src/services/langHints.js
//
// Purpose:
// - categoryMap: keywords for your BASE interest keys (e.g., "Travel", "Food", "Culture") in the target language
// - subtypeMap: keywords for your SUB interest labels (the part after ":" in your DB keys)
//
// How to use (recommended in your recommendations.service):
// const { categoryMap, subtypeMap, learnStop } = getHints(user.targetLanguage);
// const [base, sub] = String(interestKey).split(":");
// const terms = [...(categoryMap[base]||[]), ...(subtypeMap[sub]||[])];

const HINTS = {
  English: {
    learnStop: ["learn", "lesson", "lessons", "course", "beginner", "grammar", "a1", "a2"],
    categoryMap: {
      Entertainment: ["series", "tv", "movies", "interviews", "late night", "comedy", "clips"],
      Music: ["music", "songs", "live"],
      Gaming: ["gaming", "gameplay", "walkthrough", "stream"],
      Culture: ["culture", "society", "daily life", "documentary"],
      Podcasts: ["podcast", "long talk", "interview"],
      Food: ["food", "cooking", "restaurant", "street food"],
      Travel: ["travel", "vlog", "tourism"],
      Relationships: ["dating", "relationships", "social life", "advice"],
      "Self-development": ["self improvement", "motivation", "psychology", "productivity", "philosophy"],
    },
    subtypeMap: {
      // Entertainment
      Series: ["series", "tv show"],
      Movies: ["movies", "film"],
      Anime: ["anime"],
      "Reality shows": ["reality show"],
      "Drama clips": ["drama clips"],
      Interviews: ["interview"],
      "Late night": ["late night"],
      "Stand-up": ["stand up", "stand-up"],
      Sketches: ["comedy sketches"],
      // Music
      Pop: ["pop"],
      "Rap": ["rap", "hip hop", "hip-hop"],
      Rock: ["rock"],
      Electronic: ["electronic", "edm"],
      Indie: ["indie"],
      Live: ["live"],
      // Gaming
      "Story games": ["story game", "narrative"],
      Walkthroughs: ["walkthrough"],
      Streams: ["live stream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esports"],
      // Culture
      "Street interviews": ["street interview"],
      "Daily life": ["daily life vlog", "day in the life"],
      Traditions: ["traditions", "culture"],
      History: ["history"],
      Documentaries: ["documentary"],
      "News commentary": ["news commentary"],
      "Social topics": ["social issues"],
      // Podcasts
      General: ["podcast"],
      Debates: ["debate"],
      Storytelling: ["storytelling"],
      // Food
      "Food reviews": ["food review"],
      "Street food": ["street food"],
      "Restaurant vlogs": ["restaurant vlog"],
      "Cooking shows": ["cooking"],
      // Travel
      "City trips": ["city trip"],
      Nature: ["nature"],
      "Food travel": ["food travel"],
      "Budget travel": ["budget travel"],
      Relocation: ["living abroad", "relocation"],
      // Relationships
      Dating: ["dating"],
      Friendship: ["friendship"],
      Family: ["family"],
      Advice: ["advice"],
      // Self-development
      Motivation: ["motivation"],
      Psychology: ["psychology"],
      Productivity: ["productivity"],
      Philosophy: ["philosophy"],
    },
  },

  French: {
    learnStop: ["apprendre", "cours", "leçon", "débutant", "grammaire", "a1", "a2"],
    categoryMap: {
      Entertainment: ["séries", "tv", "films", "interviews", "late show", "humour", "extraits"],
      Music: ["musique", "chansons", "live"],
      Gaming: ["jeux vidéo", "gaming", "gameplay", "walkthrough", "stream"],
      Culture: ["culture", "société", "vie quotidienne", "documentaire"],
      Podcasts: ["podcast", "discussion", "interview longue"],
      Food: ["cuisine", "restaurant", "street food", "nourriture"],
      Travel: ["voyage", "vlog", "tourisme"],
      Relationships: ["relations", "rencontres", "vie sociale", "conseils"],
      "Self-development": ["développement personnel", "motivation", "psychologie", "productivité", "philosophie"],
    },
    subtypeMap: {
      Series: ["série", "séries"],
      Movies: ["film", "films"],
      Anime: ["anime"],
      "Reality shows": ["téléréalité"],
      "Drama clips": ["extraits", "scènes"],
      Interviews: ["interview"],
      "Late night": ["late show"],
      "Stand-up": ["stand-up", "one-man-show"],
      Sketches: ["sketch", "sketches"],
      Pop: ["pop"],
      Rap: ["rap", "hip-hop"],
      Rock: ["rock"],
      Electronic: ["électro", "edm"],
      Indie: ["indé", "indie"],
      Live: ["live"],
      "Story games": ["jeu narratif"],
      Walkthroughs: ["soluce", "walkthrough"],
      Streams: ["stream", "live"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esport"],
      "Street interviews": ["micro-trottoir"],
      "Daily life": ["vlog", "vie quotidienne"],
      Traditions: ["traditions"],
      History: ["histoire"],
      Documentaries: ["documentaire"],
      "News commentary": ["actu", "analyse", "commentaire"],
      "Social topics": ["sujets de société"],
      General: ["podcast"],
      Debates: ["débat"],
      Storytelling: ["récit", "storytelling"],
      "Food reviews": ["test", "review", "critique"],
      "Street food": ["street food"],
      "Restaurant vlogs": ["vlog restaurant"],
      "Cooking shows": ["cuisine"],
      "City trips": ["city trip", "visite de ville"],
      Nature: ["nature"],
      "Food travel": ["voyage culinaire"],
      "Budget travel": ["voyage pas cher"],
      Relocation: ["expatriation", "vivre à l'étranger"],
      Dating: ["rencontres"],
      Friendship: ["amitié"],
      Family: ["famille"],
      Advice: ["conseils"],
      Motivation: ["motivation"],
      Psychology: ["psychologie"],
      Productivity: ["productivité"],
      Philosophy: ["philosophie"],
    },
  },

  Spanish: {
    learnStop: ["aprender", "clase", "lección", "curso", "principiante", "gramática", "a1", "a2"],
    categoryMap: {
      Entertainment: ["series", "tv", "películas", "entrevistas", "late night", "comedia", "clips"],
      Music: ["música", "canciones", "en vivo"],
      Gaming: ["videojuegos", "gaming", "gameplay", "directo", "guía"],
      Culture: ["cultura", "sociedad", "vida diaria", "documental"],
      Podcasts: ["podcast", "charla", "entrevista larga"],
      Food: ["comida", "cocina", "restaurante", "comida callejera"],
      Travel: ["viajes", "vlog", "turismo"],
      Relationships: ["relaciones", "citas", "vida social", "consejos"],
      "Self-development": ["desarrollo personal", "motivación", "psicología", "productividad", "filosofía"],
    },
    subtypeMap: {
      Series: ["series"],
      Movies: ["películas", "cine"],
      Anime: ["anime"],
      "Reality shows": ["reality", "telerrealidad"],
      "Drama clips": ["clips", "escenas"],
      Interviews: ["entrevista", "entrevistas"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up", "monólogo"],
      Sketches: ["sketch", "sketches"],
      Pop: ["pop"],
      Rap: ["rap", "hip hop"],
      Rock: ["rock"],
      Electronic: ["electrónica", "edm"],
      Indie: ["indie"],
      Live: ["en vivo", "directo"],
      "Story games": ["juego de historia", "narrativo"],
      Walkthroughs: ["walkthrough", "guía", "paso a paso"],
      Streams: ["stream", "directo"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esports", "eSports"],
      "Street interviews": ["entrevistas callejeras"],
      "Daily life": ["vlog", "vida diaria"],
      Traditions: ["tradiciones"],
      History: ["historia"],
      Documentaries: ["documental", "documentales"],
      "News commentary": ["comentario de noticias", "análisis"],
      "Social topics": ["temas sociales"],
      General: ["podcast"],
      Debates: ["debate"],
      Storytelling: ["narración", "historias"],
      "Food reviews": ["reseña", "review"],
      "Street food": ["comida callejera"],
      "Restaurant vlogs": ["vlog restaurante"],
      "Cooking shows": ["cocina"],
      "City trips": ["viaje urbano", "ciudad"],
      Nature: ["naturaleza"],
      "Food travel": ["viaje gastronómico"],
      "Budget travel": ["viaje barato"],
      Relocation: ["vivir en el extranjero", "mudanza"],
      Dating: ["citas"],
      Friendship: ["amistad"],
      Family: ["familia"],
      Advice: ["consejos"],
      Motivation: ["motivación"],
      Psychology: ["psicología"],
      Productivity: ["productividad"],
      Philosophy: ["filosofía"],
    },
  },

  German: {
    learnStop: ["lernen", "unterricht", "lektion", "kurs", "anfänger", "grammatik", "a1", "a2"],
    categoryMap: {
      Entertainment: ["serien", "tv", "filme", "interviews", "late night", "komödie", "clips"],
      Music: ["musik", "lieder", "live"],
      Gaming: ["spiele", "gaming", "gameplay", "walkthrough", "stream"],
      Culture: ["kultur", "gesellschaft", "alltag", "doku"],
      Podcasts: ["podcast", "gespräch", "interview"],
      Food: ["essen", "kochen", "restaurant", "street food"],
      Travel: ["reisen", "vlog", "tourismus"],
      Relationships: ["beziehungen", "dating", "soziales", "tipps"],
      "Self-development": ["selbstentwicklung", "motivation", "psychologie", "produktivität", "philosophie"],
    },
    subtypeMap: {
      Series: ["serie", "serien"],
      Movies: ["film", "filme"],
      Anime: ["anime"],
      "Reality shows": ["reality", "reality-show"],
      "Drama clips": ["drama", "clips", "szenen"],
      Interviews: ["interview"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up", "kabarett"],
      Sketches: ["sketch", "sketche"],
      Pop: ["pop"],
      Rap: ["rap", "hip-hop"],
      Rock: ["rock"],
      Electronic: ["elektronisch", "edm"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["storyspiel", "narrativ"],
      Walkthroughs: ["walkthrough", "lösung"],
      Streams: ["stream", "livestream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esport"],
      "Street interviews": ["straßeninterview"],
      "Daily life": ["alltag", "vlog"],
      Traditions: ["traditionen"],
      History: ["geschichte"],
      Documentaries: ["dokumentation", "doku"],
      "News commentary": ["nachrichten", "analyse", "kommentar"],
      "Social topics": ["gesellschaftsthemen"],
      General: ["podcast"],
      Debates: ["debatte"],
      Storytelling: ["erzählen", "storytelling"],
      "Food reviews": ["test", "review", "kritik"],
      "Street food": ["street food"],
      "Restaurant vlogs": ["restaurant vlog"],
      "Cooking shows": ["kochen"],
      "City trips": ["städtereise"],
      Nature: ["natur"],
      "Food travel": ["kulinarik", "food travel"],
      "Budget travel": ["günstig reisen"],
      Relocation: ["auswandern", "umzug"],
      Dating: ["dating"],
      Friendship: ["freundschaft"],
      Family: ["familie"],
      Advice: ["tipps", "ratgeber"],
      Motivation: ["motivation"],
      Psychology: ["psychologie"],
      Productivity: ["produktivität"],
      Philosophy: ["philosophie"],
    },
  },

  Italian: {
    learnStop: ["imparare", "lezione", "lezioni", "corso", "principiante", "grammatica", "a1", "a2"],
    categoryMap: {
      Entertainment: ["serie", "tv", "film", "interviste", "late night", "comicità", "clip"],
      Music: ["musica", "canzoni", "live"],
      Gaming: ["videogiochi", "gaming", "gameplay", "guida", "stream"],
      Culture: ["cultura", "società", "vita quotidiana", "documentario"],
      Podcasts: ["podcast", "chiacchierata", "intervista lunga"],
      Food: ["cibo", "cucina", "ristorante", "street food"],
      Travel: ["viaggi", "vlog", "turismo"],
      Relationships: ["relazioni", "appuntamenti", "vita sociale", "consigli"],
      "Self-development": ["sviluppo personale", "motivazione", "psicologia", "produttività", "filosofia"],
    },
    subtypeMap: {
      Series: ["serie"],
      Movies: ["film", "cinema"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["clip", "scene"],
      Interviews: ["intervista", "interviste"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up", "monologo"],
      Sketches: ["sketch"],
      Pop: ["pop"],
      Rap: ["rap", "hip hop"],
      Rock: ["rock"],
      Electronic: ["elettronica", "edm"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["gioco narrativo"],
      Walkthroughs: ["walkthrough", "guida"],
      Streams: ["stream", "diretta"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esports"],
      "Street interviews": ["interviste in strada"],
      "Daily life": ["vita quotidiana", "vlog"],
      Traditions: ["tradizioni"],
      History: ["storia"],
      Documentaries: ["documentario"],
      "News commentary": ["commento notizie", "analisi"],
      "Social topics": ["temi sociali"],
      General: ["podcast"],
      Debates: ["dibattito"],
      Storytelling: ["narrazione"],
      "Food reviews": ["recensione", "review"],
      "Street food": ["street food"],
      "Restaurant vlogs": ["vlog ristorante"],
      "Cooking shows": ["cucina"],
      "City trips": ["viaggio in città"],
      Nature: ["natura"],
      "Food travel": ["viaggio gastronomico"],
      "Budget travel": ["viaggio low cost"],
      Relocation: ["vivere all'estero", "trasferimento"],
      Dating: ["appuntamenti"],
      Friendship: ["amicizia"],
      Family: ["famiglia"],
      Advice: ["consigli"],
      Motivation: ["motivazione"],
      Psychology: ["psicologia"],
      Productivity: ["produttività"],
      Philosophy: ["filosofia"],
    },
  },

  Portuguese: {
    learnStop: ["aprender", "aula", "lição", "curso", "iniciante", "gramática", "a1", "a2"],
    categoryMap: {
      Entertainment: ["séries", "tv", "filmes", "entrevistas", "late night", "comédia", "clips"],
      Music: ["música", "canções", "ao vivo"],
      Gaming: ["jogos", "gaming", "gameplay", "walkthrough", "stream"],
      Culture: ["cultura", "sociedade", "dia a dia", "documentário"],
      Podcasts: ["podcast", "conversa", "entrevista longa"],
      Food: ["comida", "cozinha", "restaurante", "comida de rua"],
      Travel: ["viagem", "vlog", "turismo"],
      Relationships: ["relacionamentos", "encontros", "vida social", "conselhos"],
      "Self-development": ["desenvolvimento pessoal", "motivação", "psicologia", "produtividade", "filosofia"],
    },
    subtypeMap: {
      Series: ["séries"],
      Movies: ["filmes", "cinema"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["clipes", "cenas"],
      Interviews: ["entrevista"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up"],
      Sketches: ["sketch"],
      Pop: ["pop"],
      Rap: ["rap", "hip hop"],
      Rock: ["rock"],
      Electronic: ["eletrônica", "edm"],
      Indie: ["indie"],
      Live: ["ao vivo"],
      "Story games": ["jogo de história", "narrativo"],
      Walkthroughs: ["detonado", "walkthrough"],
      Streams: ["live", "stream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esports"],
      "Street interviews": ["entrevista de rua"],
      "Daily life": ["vlog", "dia a dia"],
      Traditions: ["tradições"],
      History: ["história"],
      Documentaries: ["documentário"],
      "News commentary": ["comentário de notícias", "análise"],
      "Social topics": ["temas sociais"],
      General: ["podcast"],
      Debates: ["debate"],
      Storytelling: ["histórias", "narração"],
      "Food reviews": ["review", "avaliação"],
      "Street food": ["comida de rua"],
      "Restaurant vlogs": ["vlog restaurante"],
      "Cooking shows": ["cozinha"],
      "City trips": ["viagem urbana"],
      Nature: ["natureza"],
      "Food travel": ["viagem gastronômica"],
      "Budget travel": ["viagem barata"],
      Relocation: ["morar fora", "mudança"],
      Dating: ["encontros"],
      Friendship: ["amizade"],
      Family: ["família"],
      Advice: ["conselhos"],
      Motivation: ["motivação"],
      Psychology: ["psicologia"],
      Productivity: ["produtividade"],
      Philosophy: ["filosofia"],
    },
  },

  "Mandarin Chinese": {
    learnStop: ["学习", "课程", "教程", "入门", "初学", "语法", "A1", "A2", "教学"],
    categoryMap: {
      Entertainment: ["电视剧", "综艺", "电影", "采访", "喜剧", "片段"],
      Music: ["音乐", "歌曲", "现场"],
      Gaming: ["游戏", "游戏实况", "攻略", "直播"],
      Culture: ["文化", "社会", "日常生活", "纪录片"],
      Podcasts: ["播客", "长谈", "访谈"],
      Food: ["美食", "做饭", "餐厅", "街头美食"],
      Travel: ["旅行", "旅游", "vlog", "探店"],
      Relationships: ["恋爱", "关系", "社交", "建议"],
      "Self-development": ["自我提升", "动力", "心理学", "效率", "哲学"],
    },
    subtypeMap: {
      Series: ["电视剧"],
      Movies: ["电影"],
      Anime: ["动漫"],
      "Reality shows": ["综艺"],
      "Drama clips": ["片段"],
      Interviews: ["采访", "访谈"],
      "Late night": ["深夜节目"],
      "Stand-up": ["脱口秀"],
      Sketches: ["小品", "短剧"],
      Pop: ["流行"],
      Rap: ["说唱"],
      Rock: ["摇滚"],
      Electronic: ["电子音乐"],
      Indie: ["独立音乐"],
      Live: ["现场"],
      "Story games": ["剧情向", "故事"],
      Walkthroughs: ["攻略"],
      Streams: ["直播"],
      FPS: ["FPS"],
      RPG: ["RPG"],
      Minecraft: ["我的世界"],
      Esports: ["电竞"],
      "Street interviews": ["街头采访"],
      "Daily life": ["日常", "vlog"],
      Traditions: ["传统文化"],
      History: ["历史"],
      Documentaries: ["纪录片"],
      "News commentary": ["新闻评论", "解读"],
      "Social topics": ["社会话题"],
      General: ["播客"],
      Debates: ["辩论"],
      Storytelling: ["讲故事"],
      "Food reviews": ["美食测评"],
      "Street food": ["街头美食"],
      "Restaurant vlogs": ["探店", "餐厅vlog"],
      "Cooking shows": ["做饭", "烹饪"],
      "City trips": ["城市旅行"],
      Nature: ["自然"],
      "Food travel": ["美食之旅"],
      "Budget travel": ["穷游"],
      Relocation: ["移居", "海外生活"],
      Dating: ["恋爱", "约会"],
      Friendship: ["友情"],
      Family: ["家庭"],
      Advice: ["建议"],
      Motivation: ["动力"],
      Psychology: ["心理学"],
      Productivity: ["效率"],
      Philosophy: ["哲学"],
    },
  },

  Arabic: {
    learnStop: ["تعلم", "درس", "دروس", "دورة", "مبتدئ", "قواعد", "A1", "A2"],
    categoryMap: {
      Entertainment: ["مسلسلات", "أفلام", "مقابلات", "كوميديا", "مقاطع"],
      Music: ["موسيقى", "أغاني"],
      Gaming: ["ألعاب", "جيمينج", "قيمينغ", "بث مباشر"],
      Culture: ["ثقافة", "مجتمع", "حياة يومية", "وثائقي"],
      Podcasts: ["بودكاست", "حوارات", "مقابلات طويلة"],
      Food: ["أكل", "طبخ", "مطاعم", "أكل الشارع"],
      Travel: ["سفر", "رحلات", "فلوق", "فلوغ"],
      Relationships: ["علاقات", "مواعدة", "حياة اجتماعية", "نصائح"],
      "Self-development": ["تطوير الذات", "تحفيز", "علم النفس", "إنتاجية", "فلسفة"],
    },
    subtypeMap: {
      Series: ["مسلسلات"],
      Movies: ["أفلام"],
      Anime: ["أنمي"],
      "Reality shows": ["برامج واقع"],
      "Drama clips": ["مقاطع"],
      Interviews: ["مقابلات"],
      "Late night": ["سهرة", "برنامج ليلي"],
      "Stand-up": ["ستاند أب", "كوميديا"],
      Sketches: ["اسكتشات"],
      Pop: ["بوب"],
      Rap: ["راب"],
      Rock: ["روك"],
      Electronic: ["إلكتروني"],
      Indie: ["إندي"],
      Live: ["لايف", "مباشر"],
      "Story games": ["قصة", "قصص"],
      Walkthroughs: ["شرح", "Walkthrough"],
      Streams: ["بث مباشر"],
      FPS: ["FPS"],
      RPG: ["RPG"],
      Minecraft: ["ماينكرافت"],
      Esports: ["رياضات إلكترونية"],
      "Street interviews": ["مقابلات الشارع"],
      "Daily life": ["حياة يومية", "فلوق"],
      Traditions: ["تقاليد"],
      History: ["تاريخ"],
      Documentaries: ["وثائقي"],
      "News commentary": ["تعليق أخبار", "تحليل"],
      "Social topics": ["قضايا اجتماعية"],
      General: ["بودكاست"],
      Debates: ["مناظرة", "نقاش"],
      Storytelling: ["قصص"],
      "Food reviews": ["تجربة", "مراجعة"],
      "Street food": ["أكل الشارع"],
      "Restaurant vlogs": ["فلوق مطاعم"],
      "Cooking shows": ["طبخ"],
      "City trips": ["رحلات مدينة"],
      Nature: ["طبيعة"],
      "Food travel": ["سفر للأكل", "رحلة طعام"],
      "Budget travel": ["سفر اقتصادي"],
      Relocation: ["العيش بالخارج", "هجرة"],
      Dating: ["مواعدة"],
      Friendship: ["صداقة"],
      Family: ["عائلة"],
      Advice: ["نصائح"],
      Motivation: ["تحفيز"],
      Psychology: ["علم النفس"],
      Productivity: ["إنتاجية"],
      Philosophy: ["فلسفة"],
    },
  },

  Russian: {
    learnStop: ["учить", "урок", "уроки", "курс", "начинающий", "начинающих", "грамматика", "a1", "a2"],
    categoryMap: {
      Entertainment: ["сериалы", "фильмы", "интервью", "комедия", "клипы", "шоу"],
      Music: ["музыка", "песни", "концерт"],
      Gaming: ["игры", "геймплей", "прохождение", "стрим"],
      Culture: ["культура", "общество", "повседневная жизнь", "документальный"],
      Podcasts: ["подкаст", "длинные разговоры", "интервью"],
      Food: ["еда", "готовка", "ресторан", "уличная еда"],
      Travel: ["путешествия", "влог", "туризм"],
      Relationships: ["отношения", "свидания", "социальная жизнь", "советы"],
      "Self-development": ["саморазвитие", "мотивация", "психология", "продуктивность", "философия"],
    },
    subtypeMap: {
      Series: ["сериал", "сериалы"],
      Movies: ["фильм", "фильмы"],
      Anime: ["аниме"],
      "Reality shows": ["реалити"],
      "Drama clips": ["сцены", "клипы"],
      Interviews: ["интервью"],
      "Late night": ["вечернее шоу"],
      "Stand-up": ["стендап"],
      Sketches: ["скетчи"],
      Pop: ["поп"],
      Rap: ["рэп", "хип-хоп"],
      Rock: ["рок"],
      Electronic: ["электронная музыка"],
      Indie: ["инди"],
      Live: ["вживую", "лайв"],
      "Story games": ["сюжетные игры", "история"],
      Walkthroughs: ["прохождение"],
      Streams: ["стрим"],
      FPS: ["шутер", "fps"],
      RPG: ["rpg"],
      Minecraft: ["майнкрафт"],
      Esports: ["киберспорт"],
      "Street interviews": ["уличные интервью"],
      "Daily life": ["влог", "повседневная жизнь"],
      Traditions: ["традиции"],
      History: ["история"],
      Documentaries: ["документальный", "документалка"],
      "News commentary": ["комментарии новостей", "разбор"],
      "Social topics": ["социальные темы"],
      General: ["подкаст"],
      Debates: ["дебаты"],
      Storytelling: ["истории", "рассказы"],
      "Food reviews": ["обзор еды"],
      "Street food": ["уличная еда"],
      "Restaurant vlogs": ["влог ресторан"],
      "Cooking shows": ["готовка", "кулинария"],
      "City trips": ["поездка по городу"],
      Nature: ["природа"],
      "Food travel": ["гастротур"],
      "Budget travel": ["бюджетное путешествие"],
      Relocation: ["переезд", "жизнь за границей"],
      Dating: ["свидания"],
      Friendship: ["дружба"],
      Family: ["семья"],
      Advice: ["советы"],
      Motivation: ["мотивация"],
      Psychology: ["психология"],
      Productivity: ["продуктивность"],
      Philosophy: ["философия"],
    },
  },

  Japanese: {
    learnStop: ["勉強", "学習", "初心者", "入門", "文法", "レッスン", "講座", "A1", "A2"],
    categoryMap: {
      Entertainment: ["ドラマ", "バラエティ", "映画", "インタビュー", "お笑い", "切り抜き"],
      Music: ["音楽", "曲", "歌", "ライブ"],
      Gaming: ["ゲーム", "ゲーム実況", "配信", "攻略"],
      Culture: ["文化", "社会", "日常", "ドキュメンタリー"],
      Podcasts: ["ポッドキャスト", "対談", "長話"],
      Food: ["料理", "食レポ", "屋台", "レストラン", "グルメ"],
      Travel: ["旅行", "観光", "旅vlog", "散歩"],
      Relationships: ["恋愛", "デート", "人間関係", "相談"],
      "Self-development": ["自己啓発", "モチベーション", "心理学", "生産性", "哲学"],
    },
    subtypeMap: {
      Series: ["ドラマ"],
      Movies: ["映画"],
      Anime: ["アニメ"],
      "Reality shows": ["バラエティ"],
      "Drama clips": ["切り抜き", "名場面"],
      Interviews: ["インタビュー"],
      "Late night": ["深夜番組"],
      "Stand-up": ["漫才", "スタンドアップ"],
      Sketches: ["コント"],
      Pop: ["ポップ"],
      Rap: ["ラップ", "ヒップホップ"],
      Rock: ["ロック"],
      Electronic: ["EDM", "電子音楽"],
      Indie: ["インディー"],
      Live: ["ライブ"],
      "Story games": ["ストーリー", "物語"],
      Walkthroughs: ["攻略"],
      Streams: ["配信", "生放送"],
      FPS: ["FPS"],
      RPG: ["RPG"],
      Minecraft: ["マインクラフト"],
      Esports: ["eスポーツ"],
      "Street interviews": ["街頭インタビュー"],
      "Daily life": ["日常", "vlog"],
      Traditions: ["伝統", "文化"],
      History: ["歴史"],
      Documentaries: ["ドキュメンタリー"],
      "News commentary": ["ニュース解説", "時事"],
      "Social topics": ["社会問題"],
      General: ["ポッドキャスト"],
      Debates: ["討論"],
      Storytelling: ["語り", "ストーリー"],
      "Food reviews": ["食レポ"],
      "Street food": ["屋台", "食べ歩き"],
      "Restaurant vlogs": ["飲食店vlog", "グルメvlog"],
      "Cooking shows": ["料理"],
      "City trips": ["街歩き"],
      Nature: ["自然"],
      "Food travel": ["グルメ旅"],
      "Budget travel": ["節約旅行"],
      Relocation: ["海外移住", "引っ越し"],
      Dating: ["恋愛", "デート"],
      Friendship: ["友達"],
      Family: ["家族"],
      Advice: ["相談", "アドバイス"],
      Motivation: ["モチベ"],
      Psychology: ["心理学"],
      Productivity: ["生産性"],
      Philosophy: ["哲学"],
    },
  },

  Korean: {
    learnStop: ["배우기", "학습", "초보", "입문", "문법", "수업", "강의", "A1", "A2"],
    categoryMap: {
      Entertainment: ["드라마", "예능", "영화", "인터뷰", "코미디", "클립"],
      Music: ["음악", "노래", "라이브"],
      Gaming: ["게임", "게임플레이", "공략", "스트리밍"],
      Culture: ["문화", "사회", "일상", "다큐"],
      Podcasts: ["팟캐스트", "대담", "장시간 토크"],
      Food: ["먹방", "요리", "맛집", "길거리 음식"],
      Travel: ["여행", "브이로그", "관광"],
      Relationships: ["연애", "관계", "조언", "사회생활"],
      "Self-development": ["자기계발", "동기부여", "심리학", "생산성", "철학"],
    },
    subtypeMap: {
      Series: ["드라마"],
      Movies: ["영화"],
      Anime: ["애니"],
      "Reality shows": ["예능", "리얼리티"],
      "Drama clips": ["클립", "하이라이트"],
      Interviews: ["인터뷰"],
      "Late night": ["심야", "야간 토크쇼"],
      "Stand-up": ["스탠드업", "코미디"],
      Sketches: ["코미디 스케치"],
      Pop: ["팝"],
      Rap: ["랩", "힙합"],
      Rock: ["록"],
      Electronic: ["EDM", "일렉"],
      Indie: ["인디"],
      Live: ["라이브"],
      "Story games": ["스토리", "서사"],
      Walkthroughs: ["공략"],
      Streams: ["라이브", "스트림"],
      FPS: ["FPS"],
      RPG: ["RPG"],
      Minecraft: ["마인크래프트"],
      Esports: ["e스포츠"],
      "Street interviews": ["길거리 인터뷰"],
      "Daily life": ["일상", "브이로그"],
      Traditions: ["전통"],
      History: ["역사"],
      Documentaries: ["다큐"],
      "News commentary": ["뉴스 해설"],
      "Social topics": ["사회 이슈"],
      General: ["팟캐스트"],
      Debates: ["토론"],
      Storytelling: ["스토리텔링"],
      "Food reviews": ["리뷰", "맛평가"],
      "Street food": ["길거리 음식"],
      "Restaurant vlogs": ["맛집 브이로그"],
      "Cooking shows": ["요리"],
      "City trips": ["도시 여행"],
      Nature: ["자연"],
      "Food travel": ["먹방 여행", "맛 여행"],
      "Budget travel": ["저예산 여행"],
      Relocation: ["이민", "해외살이"],
      Dating: ["연애"],
      Friendship: ["우정"],
      Family: ["가족"],
      Advice: ["조언"],
      Motivation: ["동기부여"],
      Psychology: ["심리학"],
      Productivity: ["생산성"],
      Philosophy: ["철학"],
    },
  },

  Hindi: {
    learnStop: ["सीखें", "सीखना", "पाठ", "कोर्स", "शुरुआती", "व्याकरण", "A1", "A2"],
    categoryMap: {
      Entertainment: ["सीरीज़", "टीवी", "फिल्में", "इंटरव्यू", "कॉमेडी", "क्लिप्स"],
      Music: ["संगीत", "गाने", "लाइव"],
      Gaming: ["गेमिंग", "गेमप्ले", "वॉकथ्रू", "स्ट्रीम"],
      Culture: ["संस्कृति", "समाज", "दैनिक जीवन", "डॉक्यूमेंट्री"],
      Podcasts: ["पॉडकास्ट", "लंबी बातचीत", "इंटरव्यू"],
      Food: ["खाना", "कुकिंग", "रेस्टोरेंट", "स्ट्रीट फूड"],
      Travel: ["यात्रा", "ट्रैवल", "व्लॉग", "पर्यटन"],
      Relationships: ["रिश्ते", "डेटिंग", "सलाह"],
      "Self-development": ["सेल्फ डेवेलपमेंट", "मोटिवेशन", "मनोविज्ञान", "उत्पादकता", "दर्शन"],
    },
    subtypeMap: {
      Series: ["सीरीज़"],
      Movies: ["फिल्में"],
      Anime: ["एनीमे"],
      "Reality shows": ["रियलिटी शो"],
      "Drama clips": ["क्लिप्स", "सीन"],
      Interviews: ["इंटरव्यू"],
      "Late night": ["लेट नाइट"],
      "Stand-up": ["स्टैंडअप"],
      Sketches: ["स्केच"],
      Pop: ["पॉप"],
      Rap: ["रैप", "हिप हॉप"],
      Rock: ["रॉक"],
      Electronic: ["इलेक्ट्रॉनिक", "EDM"],
      Indie: ["इंडी"],
      Live: ["लाइव"],
      "Story games": ["कहानी", "स्टोरी गेम"],
      Walkthroughs: ["वॉकथ्रू", "गाइड"],
      Streams: ["स्ट्रीम"],
      FPS: ["FPS"],
      RPG: ["RPG"],
      Minecraft: ["माइनक्राफ्ट"],
      Esports: ["ईस्पोर्ट्स"],
      "Street interviews": ["सड़क इंटरव्यू"],
      "Daily life": ["दैनिक जीवन", "व्लॉग"],
      Traditions: ["परंपरा"],
      History: ["इतिहास"],
      Documentaries: ["डॉक्यूमेंट्री"],
      "News commentary": ["समाचार विश्लेषण"],
      "Social topics": ["सामाजिक मुद्दे"],
      General: ["पॉडकास्ट"],
      Debates: ["बहस"],
      Storytelling: ["कहानी सुनाना"],
      "Food reviews": ["रिव्यू"],
      "Street food": ["स्ट्रीट फूड"],
      "Restaurant vlogs": ["रेस्टोरेंट व्लॉग"],
      "Cooking shows": ["कुकिंग"],
      "City trips": ["शहर यात्रा"],
      Nature: ["प्रकृति"],
      "Food travel": ["फूड ट्रैवल"],
      "Budget travel": ["बजट ट्रैवल"],
      Relocation: ["विदेश में रहना", "स्थानांतरण"],
      Dating: ["डेटिंग"],
      Friendship: ["दोस्ती"],
      Family: ["परिवार"],
      Advice: ["सलाह"],
      Motivation: ["मोटिवेशन"],
      Psychology: ["मनोविज्ञान"],
      Productivity: ["उत्पादकता"],
      Philosophy: ["दर्शन"],
    },
  },

  Thai: {
    learnStop: ["เรียน", "บทเรียน", "คอร์ส", "มือใหม่", "ไวยากรณ์", "A1", "A2", "สอน"],
    categoryMap: {
      Entertainment: ["ซีรีส์", "หนัง", "สัมภาษณ์", "ตลก", "คลิป"],
      Music: ["เพลง", "ดนตรี", "ไลฟ์"],
      Gaming: ["เกม", "เกมเพลย์", "สตรีม", "ไกด์"],
      Culture: ["วัฒนธรรม", "สังคม", "ชีวิตประจำวัน", "สารคดี"],
      Podcasts: ["พอดแคสต์", "คุยยาว", "สัมภาษณ์ยาว"],
      Food: ["อาหาร", "ทำอาหาร", "ร้านอาหาร", "สตรีทฟู้ด"],
      Travel: ["เที่ยว", "ท่องเที่ยว", "vlog"],
      Relationships: ["ความสัมพันธ์", "เดท", "คำแนะนำ"],
      "Self-development": ["พัฒนาตัวเอง", "แรงบันดาลใจ", "จิตวิทยา", "ประสิทธิภาพ", "ปรัชญา"],
    },
    subtypeMap: {
      Series: ["ซีรีส์"],
      Movies: ["หนัง", "ภาพยนตร์"],
      Anime: ["อนิเมะ"],
      "Reality shows": ["เรียลลิตี้"],
      "Drama clips": ["คลิป", "ฉาก"],
      Interviews: ["สัมภาษณ์"],
      "Late night": ["รายการดึก"],
      "Stand-up": ["สแตนด์อัพ"],
      Sketches: ["สเก็ตช์"],
      Pop: ["ป๊อป"],
      Rap: ["แร็ป", "ฮิปฮอป"],
      Rock: ["ร็อก"],
      Electronic: ["อิเล็กทรอนิก", "EDM"],
      Indie: ["อินดี้"],
      Live: ["ไลฟ์"],
      "Story games": ["เนื้อเรื่อง", "เกมเนื้อเรื่อง"],
      Walkthroughs: ["ไกด์", "walkthrough"],
      Streams: ["สตรีม"],
      FPS: ["FPS"],
      RPG: ["RPG"],
      Minecraft: ["ไมน์คราฟต์"],
      Esports: ["อีสปอร์ต"],
      "Street interviews": ["สัมภาษณ์ข้างถนน"],
      "Daily life": ["ชีวิตประจำวัน", "vlog"],
      Traditions: ["ประเพณี"],
      History: ["ประวัติศาสตร์"],
      Documentaries: ["สารคดี"],
      "News commentary": ["วิเคราะห์ข่าว"],
      "Social topics": ["ประเด็นสังคม"],
      General: ["พอดแคสต์"],
      Debates: ["โต้วาที", "ดีเบต"],
      Storytelling: ["เล่าเรื่อง"],
      "Food reviews": ["รีวิวอาหาร"],
      "Street food": ["สตรีทฟู้ด"],
      "Restaurant vlogs": ["vlog ร้านอาหาร"],
      "Cooking shows": ["ทำอาหาร"],
      "City trips": ["เที่ยวเมือง"],
      Nature: ["ธรรมชาติ"],
      "Food travel": ["เที่ยวกิน"],
      "Budget travel": ["เที่ยวประหยัด"],
      Relocation: ["ย้ายประเทศ", "อยู่ต่างประเทศ"],
      Dating: ["เดท"],
      Friendship: ["มิตรภาพ"],
      Family: ["ครอบครัว"],
      Advice: ["คำแนะนำ"],
      Motivation: ["แรงบันดาลใจ"],
      Psychology: ["จิตวิทยา"],
      Productivity: ["ประสิทธิภาพ"],
      Philosophy: ["ปรัชญา"],
    },
  },

  Vietnamese: {
    learnStop: ["học", "bài học", "khóa học", "người mới", "ngữ pháp", "a1", "a2"],
    categoryMap: {
      Entertainment: ["phim", "series", "phỏng vấn", "hài", "clip"],
      Music: ["âm nhạc", "bài hát", "live"],
      Gaming: ["game", "gameplay", "stream", "hướng dẫn"],
      Culture: ["văn hóa", "xã hội", "đời sống", "tài liệu"],
      Podcasts: ["podcast", "trò chuyện dài", "phỏng vấn dài"],
      Food: ["ẩm thực", "nấu ăn", "nhà hàng", "đồ ăn đường phố"],
      Travel: ["du lịch", "vlog", "tham quan"],
      Relationships: ["mối quan hệ", "hẹn hò", "lời khuyên"],
      "Self-development": ["phát triển bản thân", "động lực", "tâm lý", "năng suất", "triết học"],
    },
    subtypeMap: {
      Series: ["series", "phim bộ"],
      Movies: ["phim", "điện ảnh"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["clip", "trích đoạn"],
      Interviews: ["phỏng vấn"],
      "Late night": ["talkshow đêm"],
      "Stand-up": ["stand-up"],
      Sketches: ["tiểu phẩm"],
      Pop: ["pop"],
      Rap: ["rap", "hip hop"],
      Rock: ["rock"],
      Electronic: ["electronic", "edm"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["cốt truyện", "game cốt truyện"],
      Walkthroughs: ["walkthrough", "hướng dẫn"],
      Streams: ["stream", "livestream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esports"],
      "Street interviews": ["phỏng vấn đường phố"],
      "Daily life": ["đời sống", "vlog"],
      Traditions: ["truyền thống"],
      History: ["lịch sử"],
      Documentaries: ["tài liệu", "phim tài liệu"],
      "News commentary": ["bình luận tin tức", "phân tích"],
      "Social topics": ["vấn đề xã hội"],
      General: ["podcast"],
      Debates: ["tranh luận"],
      Storytelling: ["kể chuyện"],
      "Food reviews": ["review đồ ăn"],
      "Street food": ["đồ ăn đường phố"],
      "Restaurant vlogs": ["vlog nhà hàng"],
      "Cooking shows": ["nấu ăn"],
      "City trips": ["du lịch thành phố"],
      Nature: ["thiên nhiên"],
      "Food travel": ["du lịch ẩm thực"],
      "Budget travel": ["du lịch tiết kiệm"],
      Relocation: ["sống ở nước ngoài", "định cư"],
      Dating: ["hẹn hò"],
      Friendship: ["tình bạn"],
      Family: ["gia đình"],
      Advice: ["lời khuyên"],
      Motivation: ["động lực"],
      Psychology: ["tâm lý"],
      Productivity: ["năng suất"],
      Philosophy: ["triết học"],
    },
  },

  Indonesian: {
    learnStop: ["belajar", "pelajaran", "kursus", "pemula", "tata bahasa", "a1", "a2"],
    categoryMap: {
      Entertainment: ["film", "serial", "wawancara", "komedi", "klip"],
      Music: ["musik", "lagu", "live"],
      Gaming: ["game", "gaming", "gameplay", "walkthrough", "stream"],
      Culture: ["budaya", "masyarakat", "kehidupan sehari-hari", "dokumenter"],
      Podcasts: ["podcast", "obrolan panjang", "wawancara panjang"],
      Food: ["makanan", "masak", "restoran", "street food"],
      Travel: ["travel", "wisata", "vlog"],
      Relationships: ["hubungan", "kencan", "sosial", "saran"],
      "Self-development": ["pengembangan diri", "motivasi", "psikologi", "produktivitas", "filsafat"],
    },
    subtypeMap: {
      Series: ["serial"],
      Movies: ["film"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["klip"],
      Interviews: ["wawancara"],
      "Late night": ["late night"],
      "Stand-up": ["stand up", "stand-up"],
      Sketches: ["sketsa komedi"],
      Pop: ["pop"],
      Rap: ["rap", "hip hop"],
      Rock: ["rock"],
      Electronic: ["edm", "elektronik"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["cerita", "narratif"],
      Walkthroughs: ["walkthrough", "panduan"],
      Streams: ["stream", "live"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esports"],
      "Street interviews": ["wawancara jalanan"],
      "Daily life": ["kehidupan sehari-hari", "vlog"],
      Traditions: ["tradisi"],
      History: ["sejarah"],
      Documentaries: ["dokumenter"],
      "News commentary": ["komentar berita", "analisis"],
      "Social topics": ["isu sosial"],
      General: ["podcast"],
      Debates: ["debat"],
      Storytelling: ["cerita"],
      "Food reviews": ["review makanan"],
      "Street food": ["street food"],
      "Restaurant vlogs": ["vlog restoran"],
      "Cooking shows": ["masak"],
      "City trips": ["wisata kota"],
      Nature: ["alam"],
      "Food travel": ["wisata kuliner"],
      "Budget travel": ["travel murah"],
      Relocation: ["tinggal di luar negeri", "pindah"],
      Dating: ["kencan"],
      Friendship: ["pertemanan"],
      Family: ["keluarga"],
      Advice: ["saran"],
      Motivation: ["motivasi"],
      Psychology: ["psikologi"],
      Productivity: ["produktivitas"],
      Philosophy: ["filsafat"],
    },
  },

  Bengali: {
    learnStop: ["শিখুন", "শেখা", "পাঠ", "কোর্স", "শুরুর", "ব্যাকরণ", "A1", "A2"],
    categoryMap: {
      Entertainment: ["সিরিজ", "টিভি", "চলচ্চিত্র", "ইন্টারভিউ", "কমেডি", "ক্লিপ"],
      Music: ["সঙ্গীত", "গান", "লাইভ"],
      Gaming: ["গেমিং", "গেমপ্লে", "স্ট্রিম", "গাইড"],
      Culture: ["সংস্কৃতি", "সমাজ", "দৈনন্দিন জীবন", "ডকুমেন্টারি"],
      Podcasts: ["পডকাস্ট", "দীর্ঘ আলোচনা", "ইন্টারভিউ"],
      Food: ["খাবার", "রান্না", "রেস্টুরেন্ট", "স্ট্রিট ফুড"],
      Travel: ["ভ্রমণ", "ট্রাভেল", "ভ্লগ"],
      Relationships: ["সম্পর্ক", "ডেটিং", "পরামর্শ"],
      "Self-development": ["আত্মউন্নয়ন", "প্রেরণা", "মনোবিজ্ঞান", "উৎপাদনশীলতা", "দর্শন"],
    },
    subtypeMap: {
      Series: ["সিরিজ"],
      Movies: ["চলচ্চিত্র", "ফিল্ম"],
      Anime: ["অ্যানিমে"],
      "Reality shows": ["রিয়েলিটি শো"],
      "Drama clips": ["ক্লিপ"],
      Interviews: ["ইন্টারভিউ"],
      "Late night": ["লেট নাইট"],
      "Stand-up": ["স্ট্যান্ড আপ"],
      Sketches: ["স্কেচ"],
      Pop: ["পপ"],
      Rap: ["র‌্যাপ", "হিপ হপ"],
      Rock: ["রক"],
      Electronic: ["ইলেকট্রনিক", "EDM"],
      Indie: ["ইন্ডি"],
      Live: ["লাইভ"],
      "Story games": ["গল্প", "স্টোরি গেম"],
      Walkthroughs: ["গাইড", "walkthrough"],
      Streams: ["স্ট্রিম"],
      FPS: ["FPS"],
      RPG: ["RPG"],
      Minecraft: ["মাইনক্রাফ্ট"],
      Esports: ["ইস্পোর্টস"],
      "Street interviews": ["রাস্তায় ইন্টারভিউ"],
      "Daily life": ["দৈনন্দিন জীবন", "ভ্লগ"],
      Traditions: ["ঐতিহ্য"],
      History: ["ইতিহাস"],
      Documentaries: ["ডকুমেন্টারি"],
      "News commentary": ["সংবাদ বিশ্লেষণ"],
      "Social topics": ["সামাজিক বিষয়"],
      General: ["পডকাস্ট"],
      Debates: ["বিতর্ক"],
      Storytelling: ["গল্প বলা"],
      "Food reviews": ["রিভিউ"],
      "Street food": ["স্ট্রিট ফুড"],
      "Restaurant vlogs": ["রেস্টুরেন্ট ভ্লগ"],
      "Cooking shows": ["রান্না"],
      "City trips": ["শহর ভ্রমণ"],
      Nature: ["প্রকৃতি"],
      "Food travel": ["খাবার ভ্রমণ"],
      "Budget travel": ["বাজেট ভ্রমণ"],
      Relocation: ["বিদেশে থাকা", "স্থানান্তর"],
      Dating: ["ডেটিং"],
      Friendship: ["বন্ধুত্ব"],
      Family: ["পরিবার"],
      Advice: ["পরামর্শ"],
      Motivation: ["প্রেরণা"],
      Psychology: ["মনোবিজ্ঞান"],
      Productivity: ["উৎপাদনশীলতা"],
      Philosophy: ["দর্শন"],
    },
  },

  Urdu: {
    learnStop: ["سیکھیں", "سیکھنا", "سبق", "کورس", "ابتدائی", "گرامر", "A1", "A2"],
    categoryMap: {
      Entertainment: ["ڈرامہ", "سیریز", "فلمیں", "انٹرویو", "کامیڈی", "کلپس"],
      Music: ["موسیقی", "گانے", "لائیو"],
      Gaming: ["گیمنگ", "گیم پلے", "اسٹریم", "گائیڈ"],
      Culture: ["ثقافت", "معاشرہ", "روزمرہ زندگی", "ڈاکیومنٹری"],
      Podcasts: ["پوڈکاسٹ", "لمبی گفتگو", "انٹرویو"],
      Food: ["کھانا", "پکانا", "ریسٹورنٹ", "اسٹریٹ فوڈ"],
      Travel: ["سفر", "ٹریول", "ولاگ"],
      Relationships: ["رشتے", "ڈیٹنگ", "مشورہ"],
      "Self-development": ["خود کی بہتری", "حوصلہ افزائی", "نفسیات", "پیداوری", "فلسفہ"],
    },
    subtypeMap: {
      Series: ["سیریز", "ڈرامہ"],
      Movies: ["فلمیں"],
      Anime: ["انیمے"],
      "Reality shows": ["ریئلٹی شو"],
      "Drama clips": ["کلپس"],
      Interviews: ["انٹرویو"],
      "Late night": ["لیٹ نائٹ"],
      "Stand-up": ["اسٹینڈ اپ"],
      Sketches: ["اسکیچ"],
      Pop: ["پاپ"],
      Rap: ["ریپ", "ہپ ہاپ"],
      Rock: ["راک"],
      Electronic: ["ای ڈی ایم", "الیکٹرانک"],
      Indie: ["انڈی"],
      Live: ["لائیو"],
      "Story games": ["کہانی", "اسٹوری گیم"],
      Walkthroughs: ["گائیڈ", "walkthrough"],
      Streams: ["اسٹریم"],
      FPS: ["FPS"],
      RPG: ["RPG"],
      Minecraft: ["مائنکرافٹ"],
      Esports: ["ای اسپورٹس"],
      "Street interviews": ["سڑک انٹرویو"],
      "Daily life": ["روزمرہ", "ولاگ"],
      Traditions: ["روایات"],
      History: ["تاریخ"],
      Documentaries: ["ڈاکیومنٹری"],
      "News commentary": ["خبروں کا تجزیہ"],
      "Social topics": ["سماجی موضوعات"],
      General: ["پوڈکاسٹ"],
      Debates: ["بحث"],
      Storytelling: ["کہانی سنانا"],
      "Food reviews": ["ریویو"],
      "Street food": ["اسٹریٹ فوڈ"],
      "Restaurant vlogs": ["ریسٹورنٹ ولاگ"],
      "Cooking shows": ["پکانا"],
      "City trips": ["شہری سفر"],
      Nature: ["قدرت"],
      "Food travel": ["فوڈ ٹریول"],
      "Budget travel": ["بجٹ سفر"],
      Relocation: ["بیرون ملک رہنا", "منتقلی"],
      Dating: ["ڈیٹنگ"],
      Friendship: ["دوستی"],
      Family: ["خاندان"],
      Advice: ["مشورہ"],
      Motivation: ["حوصلہ افزائی"],
      Psychology: ["نفسیات"],
      Productivity: ["پیداوری"],
      Philosophy: ["فلسفہ"],
    },
  },

  Turkish: {
    learnStop: ["öğren", "öğrenmek", "ders", "kurs", "başlangıç", "gramer", "dilbilgisi", "a1", "a2"],
    categoryMap: {
      Entertainment: ["dizi", "film", "röportaj", "komedi", "klip"],
      Music: ["müzik", "şarkı", "canlı"],
      Gaming: ["oyun", "gaming", "gameplay", "yayın", "rehber"],
      Culture: ["kültür", "toplum", "günlük hayat", "belgesel"],
      Podcasts: ["podcast", "uzun sohbet", "röportaj"],
      Food: ["yemek", "mutfak", "restoran", "sokak lezzetleri"],
      Travel: ["seyahat", "vlog", "turizm"],
      Relationships: ["ilişkiler", "flört", "sosyal hayat", "tavsiye"],
      "Self-development": ["kişisel gelişim", "motivasyon", "psikoloji", "verimlilik", "felsefe"],
    },
    subtypeMap: {
      Series: ["dizi"],
      Movies: ["film"],
      Anime: ["anime"],
      "Reality shows": ["reality", "yarışma"],
      "Drama clips": ["klip", "sahne"],
      Interviews: ["röportaj", "interview"],
      "Late night": ["gece şovu"],
      "Stand-up": ["stand-up"],
      Sketches: ["skeç"],
      Pop: ["pop"],
      Rap: ["rap", "hip hop"],
      Rock: ["rock"],
      Electronic: ["elektronik", "edm"],
      Indie: ["indie"],
      Live: ["canlı"],
      "Story games": ["hikaye", "story"],
      Walkthroughs: ["rehber", "walkthrough"],
      Streams: ["yayın", "stream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["e-spor"],
      "Street interviews": ["sokak röportajı"],
      "Daily life": ["günlük hayat", "vlog"],
      Traditions: ["gelenek"],
      History: ["tarih"],
      Documentaries: ["belgesel"],
      "News commentary": ["haber yorumu", "analiz"],
      "Social topics": ["toplumsal konular"],
      General: ["podcast"],
      Debates: ["tartışma", "debat"],
      Storytelling: ["hikaye anlatımı"],
      "Food reviews": ["inceleme", "review"],
      "Street food": ["sokak lezzetleri"],
      "Restaurant vlogs": ["restoran vlog"],
      "Cooking shows": ["yemek yapma"],
      "City trips": ["şehir gezisi"],
      Nature: ["doğa"],
      "Food travel": ["yemek gezisi"],
      "Budget travel": ["bütçe seyahat"],
      Relocation: ["yurt dışında yaşamak", "taşınma"],
      Dating: ["flört"],
      Friendship: ["arkadaşlık"],
      Family: ["aile"],
      Advice: ["tavsiye"],
      Motivation: ["motivasyon"],
      Psychology: ["psikoloji"],
      Productivity: ["verimlilik"],
      Philosophy: ["felsefe"],
    },
  },

  Polish: {
    learnStop: ["uczyć", "nauka", "lekcja", "kurs", "początkujący", "gramatyka", "a1", "a2"],
    categoryMap: {
      Entertainment: ["seriale", "filmy", "wywiady", "komedia", "klipy"],
      Music: ["muzyka", "piosenki", "na żywo"],
      Gaming: ["gry", "gaming", "gameplay", "poradnik", "stream"],
      Culture: ["kultura", "społeczeństwo", "codzienność", "dokument"],
      Podcasts: ["podcast", "długie rozmowy", "wywiad"],
      Food: ["jedzenie", "gotowanie", "restauracja", "street food"],
      Travel: ["podróże", "vlog", "turystyka"],
      Relationships: ["relacje", "randki", "porady"],
      "Self-development": ["rozwój osobisty", "motywacja", "psychologia", "produktywność", "filozofia"],
    },
    subtypeMap: {
      Series: ["seriale"],
      Movies: ["filmy"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["klipy", "sceny"],
      Interviews: ["wywiad"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up"],
      Sketches: ["skecze"],
      Pop: ["pop"],
      Rap: ["rap", "hip hop"],
      Rock: ["rock"],
      Electronic: ["edm", "elektroniczna"],
      Indie: ["indie"],
      Live: ["na żywo"],
      "Story games": ["fabularne", "historia"],
      Walkthroughs: ["poradnik", "przejście"],
      Streams: ["stream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esport"],
      "Street interviews": ["wywiad uliczny"],
      "Daily life": ["codzienność", "vlog"],
      Traditions: ["tradycje"],
      History: ["historia"],
      Documentaries: ["dokument"],
      "News commentary": ["komentarz wiadomości", "analiza"],
      "Social topics": ["tematy społeczne"],
      General: ["podcast"],
      Debates: ["debata"],
      Storytelling: ["opowieści"],
      "Food reviews": ["recenzja", "review"],
      "Street food": ["street food"],
      "Restaurant vlogs": ["vlog restauracyjny"],
      "Cooking shows": ["gotowanie"],
      "City trips": ["wycieczka miejska"],
      Nature: ["natura"],
      "Food travel": ["podróż kulinarna"],
      "Budget travel": ["tanie podróże"],
      Relocation: ["życie za granicą", "przeprowadzka"],
      Dating: ["randki"],
      Friendship: ["przyjaźń"],
      Family: ["rodzina"],
      Advice: ["porady"],
      Motivation: ["motywacja"],
      Psychology: ["psychologia"],
      Productivity: ["produktywność"],
      Philosophy: ["filozofia"],
    },
  },

  Swedish: {
    learnStop: ["lära", "lektion", "kurs", "nybörjare", "grammatik", "a1", "a2"],
    categoryMap: {
      Entertainment: ["serier", "filmer", "intervjuer", "komedi", "klipp"],
      Music: ["musik", "låtar", "live"],
      Gaming: ["spel", "gaming", "gameplay", "guide", "stream"],
      Culture: ["kultur", "samhälle", "vardagsliv", "dokumentär"],
      Podcasts: ["podcast", "långt samtal", "intervju"],
      Food: ["mat", "matlagning", "restaurang", "street food"],
      Travel: ["resa", "vlogg", "turism"],
      Relationships: ["relationer", "dejting", "råd"],
      "Self-development": ["självutveckling", "motivation", "psykologi", "produktivitet", "filosofi"],
    },
    subtypeMap: {
      Series: ["serier"],
      Movies: ["filmer"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["klipp"],
      Interviews: ["intervju"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up"],
      Sketches: ["sketcher"],
      Pop: ["pop"],
      Rap: ["rap", "hiphop"],
      Rock: ["rock"],
      Electronic: ["edm", "elektronisk"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["story", "berättelse"],
      Walkthroughs: ["genomgång", "guide"],
      Streams: ["stream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esport"],
      "Street interviews": ["gatuintervju"],
      "Daily life": ["vardagsliv", "vlogg"],
      Traditions: ["traditioner"],
      History: ["historia"],
      Documentaries: ["dokumentär"],
      "News commentary": ["nyhetsanalys"],
      "Social topics": ["samhällsfrågor"],
      General: ["podcast"],
      Debates: ["debatt"],
      Storytelling: ["berättelser"],
      "Food reviews": ["recension"],
      "Street food": ["street food"],
      "Restaurant vlogs": ["restaurangvlogg"],
      "Cooking shows": ["matlagning"],
      "City trips": ["stadsresa"],
      Nature: ["natur"],
      "Food travel": ["matresa"],
      "Budget travel": ["budgetresa"],
      Relocation: ["flytta utomlands"],
      Dating: ["dejting"],
      Friendship: ["vänskap"],
      Family: ["familj"],
      Advice: ["råd"],
      Motivation: ["motivation"],
      Psychology: ["psykologi"],
      Productivity: ["produktivitet"],
      Philosophy: ["filosofi"],
    },
  },

  Finnish: {
    learnStop: ["oppia", "opiskella", "tunti", "kurssi", "aloittelija", "kielioppi", "a1", "a2"],
    categoryMap: {
      Entertainment: ["sarjat", "elokuvat", "haastattelut", "komedia", "klipit"],
      Music: ["musiikki", "kappaleet", "live"],
      Gaming: ["pelit", "pelaaminen", "gameplay", "opas", "striimi"],
      Culture: ["kulttuuri", "yhteiskunta", "arki", "dokumentti"],
      Podcasts: ["podcast", "pitkä keskustelu", "haastattelu"],
      Food: ["ruoka", "ruoanlaitto", "ravintola", "katuruoka"],
      Travel: ["matkailu", "vlog", "turismi"],
      Relationships: ["suhteet", "deittailu", "neuvot"],
      "Self-development": ["itsensä kehittäminen", "motivaatio", "psykologia", "tuottavuus", "filosofia"],
    },
    subtypeMap: {
      Series: ["sarjat"],
      Movies: ["elokuvat"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["klipit"],
      Interviews: ["haastattelu"],
      "Late night": ["myöhäisilta"],
      "Stand-up": ["stand-up"],
      Sketches: ["sketsit"],
      Pop: ["pop"],
      Rap: ["rap"],
      Rock: ["rock"],
      Electronic: ["edm", "elektroninen"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["tarina", "story"],
      Walkthroughs: ["läpipeluu", "opas"],
      Streams: ["striimi"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esports"],
      "Street interviews": ["katuhastattelu"],
      "Daily life": ["arki", "vlog"],
      Traditions: ["perinteet"],
      History: ["historia"],
      Documentaries: ["dokumentti"],
      "News commentary": ["uutisanalyysi"],
      "Social topics": ["yhteiskunnalliset aiheet"],
      General: ["podcast"],
      Debates: ["väittely"],
      Storytelling: ["tarinankerronta"],
      "Food reviews": ["arvostelu"],
      "Street food": ["katuruoka"],
      "Restaurant vlogs": ["ravintolavlogi"],
      "Cooking shows": ["ruoanlaitto"],
      "City trips": ["kaupunkimatka"],
      Nature: ["luonto"],
      "Food travel": ["ruokamatka"],
      "Budget travel": ["budjettimatka"],
      Relocation: ["muutto ulkomaille"],
      Dating: ["deittailu"],
      Friendship: ["ystävyyys", "ystävät"],
      Family: ["perhe"],
      Advice: ["neuvot"],
      Motivation: ["motivaatio"],
      Psychology: ["psykologia"],
      Productivity: ["tuottavuus"],
      Philosophy: ["filosofia"],
    },
  },

  Romanian: {
    learnStop: ["învață", "a învăța", "lecție", "curs", "începător", "gramatică", "a1", "a2"],
    categoryMap: {
      Entertainment: ["seriale", "filme", "interviuri", "comedie", "clipuri"],
      Music: ["muzică", "cântece", "live"],
      Gaming: ["jocuri", "gaming", "gameplay", "ghid", "stream"],
      Culture: ["cultură", "societate", "viața de zi cu zi", "documentar"],
      Podcasts: ["podcast", "discuții lungi", "interviu"],
      Food: ["mâncare", "gătit", "restaurant", "street food"],
      Travel: ["călătorii", "vlog", "turism"],
      Relationships: ["relații", "dating", "sfaturi"],
      "Self-development": ["dezvoltare personală", "motivație", "psihologie", "productivitate", "filozofie"],
    },
    subtypeMap: {
      Series: ["seriale"],
      Movies: ["filme"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["clipuri", "scene"],
      Interviews: ["interviu"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up"],
      Sketches: ["sketch"],
      Pop: ["pop"],
      Rap: ["rap", "hip hop"],
      Rock: ["rock"],
      Electronic: ["edm", "electronic"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["poveste", "narațiune"],
      Walkthroughs: ["ghid", "walkthrough"],
      Streams: ["stream", "live"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esports"],
      "Street interviews": ["interviu stradal"],
      "Daily life": ["viața de zi cu zi", "vlog"],
      Traditions: ["tradiții"],
      History: ["istorie"],
      Documentaries: ["documentar"],
      "News commentary": ["comentariu știri", "analiză"],
      "Social topics": ["subiecte sociale"],
      General: ["podcast"],
      Debates: ["dezbatere"],
      Storytelling: ["povestire"],
      "Food reviews": ["recenzie"],
      "Street food": ["street food"],
      "Restaurant vlogs": ["vlog restaurant"],
      "Cooking shows": ["gătit"],
      "City trips": ["excursie urbană"],
      Nature: ["natură"],
      "Food travel": ["călătorie culinară"],
      "Budget travel": ["călătorie ieftină"],
      Relocation: ["mutare", "a trăi în străinătate"],
      Dating: ["dating"],
      Friendship: ["prietenie"],
      Family: ["familie"],
      Advice: ["sfaturi"],
      Motivation: ["motivație"],
      Psychology: ["psihologie"],
      Productivity: ["productivitate"],
      Philosophy: ["filozofie"],
    },
  },

  Dutch: {
    learnStop: ["leren", "les", "cursus", "beginner", "grammatica", "a1", "a2"],
    categoryMap: {
      Entertainment: ["series", "films", "interviews", "komedie", "clips"],
      Music: ["muziek", "liedjes", "live"],
      Gaming: ["games", "gaming", "gameplay", "gids", "stream"],
      Culture: ["cultuur", "samenleving", "dagelijks leven", "documentaire"],
      Podcasts: ["podcast", "lange gesprekken", "interview"],
      Food: ["eten", "koken", "restaurant", "street food"],
      Travel: ["reizen", "vlog", "toerisme"],
      Relationships: ["relaties", "dating", "advies"],
      "Self-development": ["zelfontwikkeling", "motivatie", "psychologie", "productiviteit", "filosofie"],
    },
    subtypeMap: {
      Series: ["series"],
      Movies: ["films"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["clips"],
      Interviews: ["interviews"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up"],
      Sketches: ["sketches"],
      Pop: ["pop"],
      Rap: ["rap", "hiphop"],
      Rock: ["rock"],
      Electronic: ["edm", "elektronisch"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["verhaal", "story game"],
      Walkthroughs: ["walkthrough", "gids"],
      Streams: ["stream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esports"],
      "Street interviews": ["straatinterview"],
      "Daily life": ["dagelijks leven", "vlog"],
      Traditions: ["tradities"],
      History: ["geschiedenis"],
      Documentaries: ["documentaire"],
      "News commentary": ["nieuwsanalyse", "commentaar"],
      "Social topics": ["maatschappelijke onderwerpen"],
      General: ["podcast"],
      Debates: ["debat"],
      Storytelling: ["verhalen"],
      "Food reviews": ["review"],
      "Street food": ["street food"],
      "Restaurant vlogs": ["restaurant vlog"],
      "Cooking shows": ["koken"],
      "City trips": ["stedenreis"],
      Nature: ["natuur"],
      "Food travel": ["culinaire reis"],
      "Budget travel": ["budget reizen"],
      Relocation: ["verhuizen", "wonen in het buitenland"],
      Dating: ["dating"],
      Friendship: ["vriendschap"],
      Family: ["familie"],
      Advice: ["advies"],
      Motivation: ["motivatie"],
      Psychology: ["psychologie"],
      Productivity: ["productiviteit"],
      Philosophy: ["filosofie"],
    },
  },

  Czech: {
    learnStop: ["učit se", "lekce", "kurz", "začátečník", "gramatika", "a1", "a2"],
    categoryMap: {
      Entertainment: ["seriály", "filmy", "rozhovory", "komedie", "klipy"],
      Music: ["hudba", "písně", "live"],
      Gaming: ["hry", "gaming", "gameplay", "návod", "stream"],
      Culture: ["kultura", "společnost", "běžný život", "dokument"],
      Podcasts: ["podcast", "dlouhé rozhovory", "interview"],
      Food: ["jídlo", "vaření", "restaurace", "street food"],
      Travel: ["cestování", "vlog", "turismus"],
      Relationships: ["vztahy", "randění", "rady"],
      "Self-development": ["seberozvoj", "motivace", "psychologie", "produktivita", "filozofie"],
    },
    subtypeMap: {
      Series: ["seriály"],
      Movies: ["filmy"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["klipy"],
      Interviews: ["rozhovor"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up"],
      Sketches: ["skeče"],
      Pop: ["pop"],
      Rap: ["rap", "hip hop"],
      Rock: ["rock"],
      Electronic: ["edm", "elektronická"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["příběhové hry"],
      Walkthroughs: ["návod", "průchod"],
      Streams: ["stream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esport"],
      "Street interviews": ["uliční rozhovory"],
      "Daily life": ["běžný život", "vlog"],
      Traditions: ["tradice"],
      History: ["historie"],
      Documentaries: ["dokument"],
      "News commentary": ["komentář k zprávám", "analýza"],
      "Social topics": ["společenská témata"],
      General: ["podcast"],
      Debates: ["debata"],
      Storytelling: ["vyprávění"],
      "Food reviews": ["recenze"],
      "Street food": ["street food"],
      "Restaurant vlogs": ["vlog restaurace"],
      "Cooking shows": ["vaření"],
      "City trips": ["výlet do města"],
      Nature: ["příroda"],
      "Food travel": ["gastronomické cestování"],
      "Budget travel": ["levné cestování"],
      Relocation: ["stěhování", "život v zahraničí"],
      Dating: ["randění"],
      Friendship: ["přátelství"],
      Family: ["rodina"],
      Advice: ["rady"],
      Motivation: ["motivace"],
      Psychology: ["psychologie"],
      Productivity: ["produktivita"],
      Philosophy: ["filozofie"],
    },
  },

  Greek: {
    learnStop: ["μαθαίνω", "μάθημα", "μαθήματα", "σεμινάριο", "αρχάριος", "γραμματική", "a1", "a2"],
    categoryMap: {
      Entertainment: ["σειρές", "ταινίες", "συνεντεύξεις", "κωμωδία", "κλιπ"],
      Music: ["μουσική", "τραγούδια", "live"],
      Gaming: ["παιχνίδια", "gaming", "gameplay", "οδηγός", "stream"],
      Culture: ["πολιτισμός", "κοινωνία", "καθημερινότητα", "ντοκιμαντέρ"],
      Podcasts: ["podcast", "μακρά συζήτηση", "συνέντευξη"],
      Food: ["φαγητό", "μαγειρική", "εστιατόριο", "street food"],
      Travel: ["ταξίδι", "vlog", "τουρισμός"],
      Relationships: ["σχέσεις", "ραντεβού", "συμβουλές"],
      "Self-development": ["αυτοβελτίωση", "κίνητρο", "ψυχολογία", "παραγωγικότητα", "φιλοσοφία"],
    },
    subtypeMap: {
      Series: ["σειρές"],
      Movies: ["ταινίες"],
      Anime: ["anime", "άνιμε"],
      "Reality shows": ["reality"],
      "Drama clips": ["κλιπ", "σκηνές"],
      Interviews: ["συνέντευξη"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up"],
      Sketches: ["σκιτς"],
      Pop: ["pop"],
      Rap: ["rap", "hip hop"],
      Rock: ["rock"],
      Electronic: ["edm", "ηλεκτρονική"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["ιστορία", "αφήγηση"],
      Walkthroughs: ["οδηγός", "walkthrough"],
      Streams: ["stream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esports"],
      "Street interviews": ["συνεντεύξεις δρόμου"],
      "Daily life": ["καθημερινότητα", "vlog"],
      Traditions: ["παραδόσεις"],
      History: ["ιστορία"],
      Documentaries: ["ντοκιμαντέρ"],
      "News commentary": ["ανάλυση ειδήσεων"],
      "Social topics": ["κοινωνικά θέματα"],
      General: ["podcast"],
      Debates: ["ντιμπέιτ", "συζήτηση"],
      Storytelling: ["αφήγηση"],
      "Food reviews": ["κριτική", "review"],
      "Street food": ["street food"],
      "Restaurant vlogs": ["vlog εστιατορίου"],
      "Cooking shows": ["μαγειρική"],
      "City trips": ["ταξίδι πόλης"],
      Nature: ["φύση"],
      "Food travel": ["γαστρονομικό ταξίδι"],
      "Budget travel": ["φθηνό ταξίδι"],
      Relocation: ["μετανάστευση", "ζωή στο εξωτερικό"],
      Dating: ["ραντεβού"],
      Friendship: ["φιλία"],
      Family: ["οικογένεια"],
      Advice: ["συμβουλές"],
      Motivation: ["κίνητρο"],
      Psychology: ["ψυχολογία"],
      Productivity: ["παραγωγικότητα"],
      Philosophy: ["φιλοσοφία"],
    },
  },

  Bulgarian: {
    learnStop: ["уча", "урок", "уроци", "курс", "начинаещ", "граматика", "a1", "a2"],
    categoryMap: {
      Entertainment: ["сериали", "филми", "интервюта", "комедия", "клипове"],
      Music: ["музика", "песни", "на живо"],
      Gaming: ["игри", "геймплей", "стрийм", "ръководство"],
      Culture: ["култура", "общество", "ежедневие", "документален"],
      Podcasts: ["подкаст", "дълги разговори", "интервю"],
      Food: ["храна", "готвене", "ресторант", "улична храна"],
      Travel: ["пътуване", "влог", "туризъм"],
      Relationships: ["отношения", "срещи", "съвети"],
      "Self-development": ["саморазвитие", "мотивация", "психология", "продуктивност", "философия"],
    },
    subtypeMap: {
      Series: ["сериали"],
      Movies: ["филми"],
      Anime: ["аниме"],
      "Reality shows": ["реалити"],
      "Drama clips": ["клипове", "сцени"],
      Interviews: ["интервю"],
      "Late night": ["късно шоу"],
      "Stand-up": ["стендъп"],
      Sketches: ["скечове"],
      Pop: ["поп"],
      Rap: ["рап", "хип-хоп"],
      Rock: ["рок"],
      Electronic: ["едм", "електронна"],
      Indie: ["инди"],
      Live: ["на живо"],
      "Story games": ["сюжет", "история"],
      Walkthroughs: ["прохождане", "ръководство"],
      Streams: ["стрийм"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["майнкрафт"],
      Esports: ["еспорт"],
      "Street interviews": ["улични интервюта"],
      "Daily life": ["ежедневие", "влог"],
      Traditions: ["традиции"],
      History: ["история"],
      Documentaries: ["документален"],
      "News commentary": ["анализ на новини"],
      "Social topics": ["социални теми"],
      General: ["подкаст"],
      Debates: ["дебат"],
      Storytelling: ["разказване"],
      "Food reviews": ["ревю", "отзив"],
      "Street food": ["улична храна"],
      "Restaurant vlogs": ["влог ресторант"],
      "Cooking shows": ["готвене"],
      "City trips": ["градско пътуване"],
      Nature: ["природа"],
      "Food travel": ["гастро пътуване"],
      "Budget travel": ["бюджетно пътуване"],
      Relocation: ["живот в чужбина", "преместване"],
      Dating: ["срещи"],
      Friendship: ["приятелство"],
      Family: ["семейство"],
      Advice: ["съвети"],
      Motivation: ["мотивация"],
      Psychology: ["психология"],
      Productivity: ["продуктивност"],
      Philosophy: ["философия"],
    },
  },

  Swahili: {
    learnStop: ["jifunza", "somo", "masomo", "kozi", "mwanzoni", "sarufi", "a1", "a2"],
    categoryMap: {
      Entertainment: ["vipindi", "filamu", "mahojiano", "vichekesho", "vipande"],
      Music: ["muziki", "nyimbo", "live"],
      Gaming: ["michezo", "gaming", "gameplay", "mwongozo", "stream"],
      Culture: ["utamaduni", "jamii", "maisha ya kila siku", "makala"],
      Podcasts: ["podcast", "mazungumzo marefu", "mahojiano"],
      Food: ["chakula", "kupika", "mgahawa", "chakula cha mtaani"],
      Travel: ["safari", "vlog", "utalii"],
      Relationships: ["mah关系", "mah关系"], // (keep simple: Swahili terms below)
      "Self-development": ["kujikuza", "motisha", "saikolojia", "tija", "falsafa"],
    },
    subtypeMap: {
      Series: ["vipindi"],
      Movies: ["filamu"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["vipande"],
      Interviews: ["mahojiano"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up"],
      Sketches: ["sketch"],
      Pop: ["pop"],
      Rap: ["rap", "hip hop"],
      Rock: ["rock"],
      Electronic: ["edm", "electronic"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["hadithi", "story"],
      Walkthroughs: ["mwongozo", "walkthrough"],
      Streams: ["stream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esports"],
      "Street interviews": ["mahojiano ya mtaani"],
      "Daily life": ["maisha ya kila siku", "vlog"],
      Traditions: ["mila"],
      History: ["historia"],
      Documentaries: ["makala", "dokumentari"],
      "News commentary": ["uchambuzi wa habari"],
      "Social topics": ["mada za kijamii"],
      General: ["podcast"],
      Debates: ["mdahalo"],
      Storytelling: ["usimulizi"],
      "Food reviews": ["mapitio", "review"],
      "Street food": ["chakula cha mtaani"],
      "Restaurant vlogs": ["vlog ya mgahawa"],
      "Cooking shows": ["kupika"],
      "City trips": ["safari ya jiji"],
      Nature: ["asili"],
      "Food travel": ["safari ya chakula"],
      "Budget travel": ["safari ya bei nafuu"],
      Relocation: ["kuishi nje", "kuhama"],
      Dating: ["uchumba", "dating"],
      Friendship: ["urafiki"],
      Family: ["familia"],
      Advice: ["ushauri"],
      Motivation: ["motisha"],
      Psychology: ["saikolojia"],
      Productivity: ["tija"],
      Philosophy: ["falsafa"],
    },
  },

  Afrikaans: {
    learnStop: ["leer", "les", "kursus", "beginner", "grammatika", "a1", "a2"],
    categoryMap: {
      Entertainment: ["reekse", "flieks", "onderhoude", "komedie", "klips"],
      Music: ["musiek", "liedjies", "live"],
      Gaming: ["speletjies", "gaming", "gameplay", "gids", "stroom"],
      Culture: ["kultuur", "samelewing", "alledaagse lewe", "dokumentêr"],
      Podcasts: ["podcast", "lang gesprek", "onderhoud"],
      Food: ["kos", "kook", "restaurant", "straatkos"],
      Travel: ["reis", "vlog", "toerisme"],
      Relationships: ["verhoudings", "dating", "raad"],
      "Self-development": ["selfontwikkeling", "motivering", "sielkunde", "produktiwiteit", "filosofie"],
    },
    subtypeMap: {
      Series: ["reekse"],
      Movies: ["flieks"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["klips"],
      Interviews: ["onderhoud"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up"],
      Sketches: ["sketse"],
      Pop: ["pop"],
      Rap: ["rap", "hip hop"],
      Rock: ["rock"],
      Electronic: ["edm", "elektronies"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["storie", "verhaal"],
      Walkthroughs: ["walkthrough", "gids"],
      Streams: ["stroom", "stream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esports"],
      "Street interviews": ["straat-onderhoude"],
      "Daily life": ["alledaagse lewe", "vlog"],
      Traditions: ["tradisies"],
      History: ["geskiedenis"],
      Documentaries: ["dokumentêr"],
      "News commentary": ["nuus-analise"],
      "Social topics": ["sosiale onderwerpe"],
      General: ["podcast"],
      Debates: ["debat"],
      Storytelling: ["vertel stories"],
      "Food reviews": ["resensie", "review"],
      "Street food": ["straatkos"],
      "Restaurant vlogs": ["restaurant vlog"],
      "Cooking shows": ["kook"],
      "City trips": ["stadsreis"],
      Nature: ["natuur"],
      "Food travel": ["kosreis"],
      "Budget travel": ["begrotingsreis"],
      Relocation: ["trek oorsee"],
      Dating: ["dating"],
      Friendship: ["vriendskap"],
      Family: ["familie"],
      Advice: ["raad"],
      Motivation: ["motivering"],
      Psychology: ["sielkunde"],
      Productivity: ["produktiwiteit"],
      Philosophy: ["filosofie"],
    },
  },

  Norwegian: {
    learnStop: ["lære", "leksjon", "kurs", "nybegynner", "grammatikk", "a1", "a2"],
    categoryMap: {
      Entertainment: ["serier", "filmer", "intervjuer", "komedie", "klipp"],
      Music: ["musikk", "sanger", "live"],
      Gaming: ["spill", "gaming", "gameplay", "guide", "stream"],
      Culture: ["kultur", "samfunn", "hverdagsliv", "dokumentar"],
      Podcasts: ["podcast", "lange samtaler", "intervju"],
      Food: ["mat", "matlaging", "restaurant", "street food"],
      Travel: ["reise", "vlogg", "turisme"],
      Relationships: ["forhold", "dating", "råd"],
      "Self-development": ["selvutvikling", "motivasjon", "psykologi", "produktivitet", "filosofi"],
    },
    subtypeMap: {
      Series: ["serier"],
      Movies: ["filmer"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["klipp"],
      Interviews: ["intervju"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up"],
      Sketches: ["sketsjer"],
      Pop: ["pop"],
      Rap: ["rap", "hiphop"],
      Rock: ["rock"],
      Electronic: ["edm", "elektronisk"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["historie", "story"],
      Walkthroughs: ["guide", "gjennomgang"],
      Streams: ["stream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esport"],
      "Street interviews": ["gateintervju"],
      "Daily life": ["hverdagsliv", "vlogg"],
      Traditions: ["tradisjoner"],
      History: ["historie"],
      Documentaries: ["dokumentar"],
      "News commentary": ["nyhetsanalyse"],
      "Social topics": ["samfunnstema"],
      General: ["podcast"],
      Debates: ["debatt"],
      Storytelling: ["fortelling"],
      "Food reviews": ["anmeldelse"],
      "Street food": ["street food"],
      "Restaurant vlogs": ["restaurant vlogg"],
      "Cooking shows": ["matlaging"],
      "City trips": ["bytur"],
      Nature: ["natur"],
      "Food travel": ["matreise"],
      "Budget travel": ["budsjett reise"],
      Relocation: ["flytte ut", "bo i utlandet"],
      Dating: ["dating"],
      Friendship: ["vennskap"],
      Family: ["familie"],
      Advice: ["råd"],
      Motivation: ["motivasjon"],
      Psychology: ["psykologi"],
      Productivity: ["produktivitet"],
      Philosophy: ["filosofi"],
    },
  },

  Tagalog: {
    learnStop: ["matuto", "aralin", "leksyon", "kurso", "baguhan", "gramatika", "a1", "a2"],
    categoryMap: {
      Entertainment: ["series", "pelikula", "interview", "komedya", "clips"],
      Music: ["musika", "mga kanta", "live"],
      Gaming: ["laro", "gaming", "gameplay", "guide", "stream"],
      Culture: ["kultura", "lipunan", "araw-araw", "dokumentaryo"],
      Podcasts: ["podcast", "mahabang usapan", "interview"],
      Food: ["pagkain", "luto", "restaurant", "street food"],
      Travel: ["biyahe", "travel", "vlog"],
      Relationships: ["relasyon", "dating", "payo"],
      "Self-development": ["pag-unlad ng sarili", "motibasyon", "sikolohiya", "produktibidad", "pilosopiya"],
    },
    subtypeMap: {
      Series: ["series"],
      Movies: ["pelikula"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["clips"],
      Interviews: ["interview"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up"],
      Sketches: ["sketch"],
      Pop: ["pop"],
      Rap: ["rap", "hip hop"],
      Rock: ["rock"],
      Electronic: ["edm", "electronic"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["kwento", "story"],
      Walkthroughs: ["guide", "walkthrough"],
      Streams: ["stream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esports"],
      "Street interviews": ["interview sa kalsada"],
      "Daily life": ["araw-araw", "vlog"],
      Traditions: ["tradisyon"],
      History: ["kasaysayan"],
      Documentaries: ["dokumentaryo"],
      "News commentary": ["pagsusuri ng balita"],
      "Social topics": ["isyu sa lipunan"],
      General: ["podcast"],
      Debates: ["debate"],
      Storytelling: ["pagkukuwento"],
      "Food reviews": ["review"],
      "Street food": ["street food"],
      "Restaurant vlogs": ["restaurant vlog"],
      "Cooking shows": ["pagluluto"],
      "City trips": ["biyahe sa siyudad"],
      Nature: ["kalikasan"],
      "Food travel": ["food travel"],
      "Budget travel": ["budget travel"],
      Relocation: ["tumira sa ibang bansa", "lipat"],
      Dating: ["dating"],
      Friendship: ["pagkakaibigan"],
      Family: ["pamilya"],
      Advice: ["payo"],
      Motivation: ["motibasyon"],
      Psychology: ["sikolohiya"],
      Productivity: ["produktibidad"],
      Philosophy: ["pilosopiya"],
    },
  },

  Ukrainian: {
    learnStop: ["вчити", "урок", "уроки", "курс", "початківець", "граматика", "a1", "a2"],
    categoryMap: {
      Entertainment: ["серіали", "фільми", "інтерв'ю", "комедія", "кліпи"],
      Music: ["музика", "пісні", "наживо"],
      Gaming: ["ігри", "геймплей", "стрім", "гайд"],
      Culture: ["культура", "суспільство", "повсякденне життя", "документальний"],
      Podcasts: ["подкаст", "довгі розмови", "інтерв'ю"],
      Food: ["їжа", "готування", "ресторан", "вулична їжа"],
      Travel: ["подорожі", "влог", "туризм"],
      Relationships: ["стосунки", "побачення", "поради"],
      "Self-development": ["саморозвиток", "мотивація", "психологія", "продуктивність", "філософія"],
    },
    subtypeMap: {
      Series: ["серіали"],
      Movies: ["фільми"],
      Anime: ["аніме"],
      "Reality shows": ["реаліті"],
      "Drama clips": ["кліпи", "сцени"],
      Interviews: ["інтерв'ю"],
      "Late night": ["пізнє шоу"],
      "Stand-up": ["стендап"],
      Sketches: ["скетчі"],
      Pop: ["поп"],
      Rap: ["реп", "хіп-хоп"],
      Rock: ["рок"],
      Electronic: ["edm", "електронна"],
      Indie: ["інді"],
      Live: ["наживо"],
      "Story games": ["сюжет", "історія"],
      Walkthroughs: ["проходження", "гайд"],
      Streams: ["стрім"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["майнкрафт"],
      Esports: ["кіберспорт"],
      "Street interviews": ["вуличні інтерв'ю"],
      "Daily life": ["повсякденне життя", "влог"],
      Traditions: ["традиції"],
      History: ["історія"],
      Documentaries: ["документальний"],
      "News commentary": ["аналіз новин"],
      "Social topics": ["соціальні теми"],
      General: ["подкаст"],
      Debates: ["дебати"],
      Storytelling: ["історії"],
      "Food reviews": ["огляд", "рев'ю"],
      "Street food": ["вулична їжа"],
      "Restaurant vlogs": ["влог ресторан"],
      "Cooking shows": ["готування"],
      "City trips": ["подорож містом"],
      Nature: ["природа"],
      "Food travel": ["гастро-подорож"],
      "Budget travel": ["бюджетна подорож"],
      Relocation: ["переїзд", "життя за кордоном"],
      Dating: ["побачення"],
      Friendship: ["дружба"],
      Family: ["сім'я"],
      Advice: ["поради"],
      Motivation: ["мотивація"],
      Psychology: ["психологія"],
      Productivity: ["продуктивність"],
      Philosophy: ["філософія"],
    },
  },

  Hebrew: {
    learnStop: ["ללמוד", "שיעור", "קורס", "מתחילים", "דקדוק", "A1", "A2"],
    categoryMap: {
      Entertainment: ["סדרות", "סרטים", "ראיונות", "קומדיה", "קליפים"],
      Music: ["מוזיקה", "שירים", "לייב"],
      Gaming: ["משחקים", "גיימינג", "גיימפליי", "סטרים"],
      Culture: ["תרבות", "חברה", "חיי יום יום", "דוקומנטרי"],
      Podcasts: ["פודקאסט", "שיחות ארוכות", "ראיונות"],
      Food: ["אוכל", "בישול", "מסעדה", "אוכל רחוב"],
      Travel: ["טיול", "וולוג", "תיירות"],
      Relationships: ["מערכות יחסים", "דייטינג", "עצות"],
      "Self-development": ["התפתחות אישית", "מוטיבציה", "פסיכולוגיה", "פרודוקטיביות", "פילוסופיה"],
    },
    subtypeMap: {
      Series: ["סדרות"],
      Movies: ["סרטים"],
      Anime: ["אנימה"],
      "Reality shows": ["ריאליטי"],
      "Drama clips": ["קליפים"],
      Interviews: ["ראיונות"],
      "Late night": ["לייט נייט"],
      "Stand-up": ["סטנדאפ"],
      Sketches: ["מערכונים"],
      Pop: ["פופ"],
      Rap: ["ראפ", "היפ הופ"],
      Rock: ["רוק"],
      Electronic: ["EDM", "אלקטרוני"],
      Indie: ["אינדי"],
      Live: ["לייב"],
      "Story games": ["סיפור", "עלילה"],
      Walkthroughs: ["מדריך", "walkthrough"],
      Streams: ["סטרים"],
      FPS: ["FPS"],
      RPG: ["RPG"],
      Minecraft: ["מיינקראפט"],
      Esports: ["איספורט"],
      "Street interviews": ["ראיונות רחוב"],
      "Daily life": ["חיי יום יום", "וולוג"],
      Traditions: ["מסורת"],
      History: ["היסטוריה"],
      Documentaries: ["דוקומנטרי"],
      "News commentary": ["ניתוח חדשות"],
      "Social topics": ["נושאים חברתיים"],
      General: ["פודקאסט"],
      Debates: ["דיבייט", "דיון"],
      Storytelling: ["סיפור סיפורים"],
      "Food reviews": ["ביקורת אוכל"],
      "Street food": ["אוכל רחוב"],
      "Restaurant vlogs": ["וולוג מסעדות"],
      "Cooking shows": ["בישול"],
      "City trips": ["טיול בעיר"],
      Nature: ["טבע"],
      "Food travel": ["טיול אוכל"],
      "Budget travel": ["טיול זול"],
      Relocation: ["לעבור לחו״ל", "רילוקיישן"],
      Dating: ["דייטינג"],
      Friendship: ["חברות"],
      Family: ["משפחה"],
      Advice: ["עצות"],
      Motivation: ["מוטיבציה"],
      Psychology: ["פסיכולוגיה"],
      Productivity: ["פרודוקטיביות"],
      Philosophy: ["פילוסופיה"],
    },
  },

  Malay: {
    learnStop: ["belajar", "pelajaran", "kursus", "pemula", "tatabahasa", "a1", "a2"],
    categoryMap: {
      Entertainment: ["siri", "filem", "temu bual", "komedi", "klip"],
      Music: ["muzik", "lagu", "live"],
      Gaming: ["permainan", "gaming", "gameplay", "panduan", "stream"],
      Culture: ["budaya", "masyarakat", "kehidupan harian", "dokumentari"],
      Podcasts: ["podcast", "sembang panjang", "temu bual"],
      Food: ["makanan", "memasak", "restoran", "makanan jalanan"],
      Travel: ["perjalanan", "vlog", "pelancongan"],
      Relationships: ["hubungan", "dating", "nasihat"],
      "Self-development": ["pembangunan diri", "motivasi", "psikologi", "produktiviti", "falsafah"],
    },
    subtypeMap: {
      Series: ["siri"],
      Movies: ["filem"],
      Anime: ["anime"],
      "Reality shows": ["reality"],
      "Drama clips": ["klip"],
      Interviews: ["temu bual"],
      "Late night": ["late night"],
      "Stand-up": ["stand-up"],
      Sketches: ["sketch"],
      Pop: ["pop"],
      Rap: ["rap", "hip hop"],
      Rock: ["rock"],
      Electronic: ["edm", "elektronik"],
      Indie: ["indie"],
      Live: ["live"],
      "Story games": ["cerita", "naratif"],
      Walkthroughs: ["panduan", "walkthrough"],
      Streams: ["stream"],
      FPS: ["fps"],
      RPG: ["rpg"],
      Minecraft: ["minecraft"],
      Esports: ["esports"],
      "Street interviews": ["temu bual jalanan"],
      "Daily life": ["kehidupan harian", "vlog"],
      Traditions: ["tradisi"],
      History: ["sejarah"],
      Documentaries: ["dokumentari"],
      "News commentary": ["ulasan berita", "analisis"],
      "Social topics": ["isu sosial"],
      General: ["podcast"],
      Debates: ["debat"],
      Storytelling: ["penceritaan"],
      "Food reviews": ["ulasan", "review"],
      "Street food": ["makanan jalanan"],
      "Restaurant vlogs": ["vlog restoran"],
      "Cooking shows": ["memasak"],
      "City trips": ["trip bandar"],
      Nature: ["alam semula jadi"],
      "Food travel": ["travel makanan"],
      "Budget travel": ["travel bajet"],
      Relocation: ["tinggal di luar negara", "pindah"],
      Dating: ["dating"],
      Friendship: ["persahabatan"],
      Family: ["keluarga"],
      Advice: ["nasihat"],
      Motivation: ["motivasi"],
      Psychology: ["psikologi"],
      Productivity: ["produktiviti"],
      Philosophy: ["falsafah"],
    },
  },

  Tamil: {
    learnStop: ["கற்றுக்கொள்", "கற்றல்", "பாடம்", "பாடங்கள்", "பாடநெறி", "தொடக்கநிலை", "இலக்கணம்", "A1", "A2"],
    categoryMap: {
      Entertainment: ["தொடர்கள்", "திரைப்படம்", "நேர்காணல்", "நகைச்சுவை", "கிளிப்"],
      Music: ["இசை", "பாடல்கள்", "லைவ்"],
      Gaming: ["விளையாட்டு", "கேமிங்", "கேம்ப்ளே", "ஸ்ட்ரீம்", "வழிகாட்டி"],
      Culture: ["கலாசாரம்", "சமூகம்", "தினசரி வாழ்க்கை", "ஆவணப்படம்"],
      Podcasts: ["பாட்காஸ்ட்", "நீண்ட உரையாடல்", "நேர்காணல்"],
      Food: ["உணவு", "சமையல்", "உணவகம்", "தெரு உணவு"],
      Travel: ["பயணம்", "டிராவல்", "வ்லாக்", "சுற்றுலா"],
      Relationships: ["உறவுகள்", "டேட்டிங்", "ஆலோசனை"],
      "Self-development": ["சுய மேம்பாடு", "மூச்சூட்டு", "உளவியல்", "திறன்", "தத்துவம்"],
    },
    subtypeMap: {
      Series: ["தொடர்கள்"],
      Movies: ["திரைப்படம்"],
      Anime: ["அனிமே"],
      "Reality shows": ["ரியாலிட்டி"],
      "Drama clips": ["கிளிப்"],
      Interviews: ["நேர்காணல்"],
      "Late night": ["இரவு நிகழ்ச்சி"],
      "Stand-up": ["ஸ்டாண்ட்-அப்"],
      Sketches: ["ஸ்கெட்ச்"],
      Pop: ["பாப்"],
      Rap: ["ரேப்", "ஹிப் ஹாப்"],
      Rock: ["ராக்"],
      Electronic: ["EDM", "எலெக்ட்ரானிக்"],
      Indie: ["இந்தி"],
      Live: ["லைவ்"],
      "Story games": ["கதை", "ஸ்டோரி"],
      Walkthroughs: ["வழிகாட்டி", "walkthrough"],
      Streams: ["ஸ்ட்ரீம்"],
      FPS: ["FPS"],
      RPG: ["RPG"],
      Minecraft: ["மைன்கிராஃப்ட்"],
      Esports: ["ஈஸ்போர்ட்ஸ்"],
      "Street interviews": ["தெரு நேர்காணல்"],
      "Daily life": ["தினசரி வாழ்க்கை", "வ்லாக்"],
      Traditions: ["மரபு"],
      History: ["வரலாறு"],
      Documentaries: ["ஆவணப்படம்"],
      "News commentary": ["செய்தி பகுப்பாய்வு"],
      "Social topics": ["சமூக தலைப்புகள்"],
      General: ["பாட்காஸ்ட்"],
      Debates: ["விவாதம்"],
      Storytelling: ["கதை சொல்லல்"],
      "Food reviews": ["ரிவ்யூ"],
      "Street food": ["தெரு உணவு"],
      "Restaurant vlogs": ["உணவகம் வ்லாக்"],
      "Cooking shows": ["சமையல்"],
      "City trips": ["நகர பயணம்"],
      Nature: ["இயற்கை"],
      "Food travel": ["உணவு பயணம்"],
      "Budget travel": ["பட்ஜெட் பயணம்"],
      Relocation: ["வெளிநாடு வாழ்வு", "இடமாற்றம்"],
      Dating: ["டேட்டிங்"],
      Friendship: ["நட்பு"],
      Family: ["குடும்பம்"],
      Advice: ["ஆலோசனை"],
      Motivation: ["மூச்சூட்டு"],
      Psychology: ["உளவியல்"],
      Productivity: ["திறன்", "உற்பத்தித்திறன்"],
      Philosophy: ["தத்துவம்"],
    },
  },
};

function getHints(languageName) {
  return (
    HINTS[languageName] || {
      learnStop: ["learn", "lesson", "course", "grammar", "beginner", "a1", "a2"],
      categoryMap: {},
      subtypeMap: {},
    }
  );
}

module.exports = { getHints };